### ISSUE TITLE
error while rendering images

### ISSUE THREAD

**Issue by mohitm1994** [zhang-zx/SINE#1]
File "SINE-master/scripts/guidance_ddim.py", line 486, in p_sample_ddim
    e_t_uncond, e_t = self.model.apply_model(
TypeError: apply_model() got an unexpected keyword argument 'crop_boxes'

**Comment by zhang-zx** [comment]
Thanks for your interest in our work. Could you please provide us with more details about how you got this error? Like the script you run and a complete log of your output.

**Comment by mohitm1994** [comment]
Hi @zhang-zx, I solved the issue. It was due to an old installation of the ldm environment.
