### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Winnie202** [zhang-zx/SINE#10]
My computer has 24G memory, but it still has the problem of CUDA out of memory,Choosing smaller pictures doesn't help either.
the command is like this:

IMG_PATH=./test_img/37.jpg
CLS_WRD='shoes'
NAME='shoes_test'

python main.py \
    --base configs/stable-diffusion/v1-finetune_patch_picture.yaml \
    -t --actual_resume ./checkpoints/sd-v1-4-full-ema.ckpt \
    -n $NAME --gpus 0,   --logdir ./logs \
    --data_root $IMG_PATH \
    --reg_data_root $IMG_PATH --class_word $CLS_WRD  

Excuse me, is there any solution?

**Comment by zhang-zx** [comment]
Hi, Thanks for your interest in our work. We haven't worked on this yet, but it could be a possible solution for you to change the optimizer to AdamW8bit. Let us know if it works.

**Comment by Winnie202** [comment]
> 

Ok, thank you for your reply

**Comment by xueqinxiang** [comment]
I have tested my solution by using A30 (GPU 24G only):

1. install bitsandbytes such as : pip3 install bitsandbytes-cuda116  ---- cuda 11.6 was installed before

2. modify the source file: .\ldm\models\diffusion\ddpm.py
   2.1 disable DDP like:
         # default to ddp
          # trainer_config["accelerator"] = "ddp"

   2.2 use Adam8bit like:
       import bitsandbytes as bnb #try to reduce GPU memory 

      #opt = torch.optim.AdamW(params, lr=lr)
      opt = bnb.optim.Adam8bit(params, lr=lr)
      
     Note that，there are 7 places need to be replaced in ddpm.py
