### ISSUE TITLE
Patch based fine tuning

### ISSUE THREAD

**Issue by JohnMe** [zhang-zx/SINE#2]
Hello, thanks for open sourcing the code. 

I'm trying to reproduce the patch based fine-tuning, but it crashes with an error about the channel dimensions. Any suggestions?

IMG_PATH='./fox.jpg'
CLS_WRD='sculpture'
NAME='name of the experiment'
MODEL_PATH='./sd-v1-4-full-ema.ckpt'

python main.py \
    --base configs/stable-diffusion/v1-finetune_patch_picture.yaml \
    -t --actual_resume $MODEL_PATH \
    -n $NAME --gpus 0,   --logdir ./logs \
    --data_root $IMG_PATH \
    --precision=16 \
    --batch_size=1 \
    --num_workers=8 \
    --max_images=1 \
    --reg_data_root $IMG_PATH --class_word $CLS_WRD  

Error:
Global seed set to 23
Running on GPUs 0,
Loading model from ./sd-v1-4-full-ema.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 64, 64) = 16384 dimensions.
making attention of type 'vanilla' with 512 in_channels
/home/a/.local/lib/python3.8/site-packages/transformers/configuration_utils.py:512: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn(
You are using a model of type clip to instantiate a model of type clip_text_model. This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):
  File "main.py", line 606, in <module>
    model = load_model_from_config(config, opt.actual_resume)
  File "main.py", line 31, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/mnt/8tb/SINE/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
  File "/mnt/8tb/SINE/ldm/models/diffusion/ddpm.py", line 480, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/mnt/8tb/SINE/ldm/models/diffusion/ddpm.py", line 566, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/mnt/8tb/SINE/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
  File "/mnt/8tb/SINE/ldm/modules/encoders/modules.py", line 162, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "/home/a/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1528, in from_pretrained
    model, missing_keys, unexpected_keys, mismatched_keys, error_msgs = cls._load_state_dict_into_model(
  File "/home/a/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1682, in _load_state_dict_into_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
	size mismatch for text_model.embeddings.token_embedding.weight: copying a param with shape torch.Size([49408, 768]) from checkpoint, the shape in current model is torch.Size([49408, 512]).
	size mismatch for text_model.embeddings.position_embedding.weight: copying a param with shape torch.Size([77, 768]) from checkpoint, the shape in current model is torch.Size([77, 512]).

**Comment by zhang-zx** [comment]
Thanks for your interest in our work. I can't reproduce the error with the information you provided. Could you please check your environment setting? Looks like there's something wrong with the CLIP model you loaded.

**Comment by JohnMe** [comment]
Thanks for your answer. I basically followed you guide:

>git clone git@github.com:zhang-zx/SINE.git

>Then, install the dependencies following the [instructions](https://github.com/CompVis/stable-diffusion#stable-diffusion-v1). To >fine-tune the model, you need to download the [pre-trained model](https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4-full-ema.ckpt).

and ended up with this:

 - python 3.8.5
    - attrs==22.1.0
    - future==0.18.2
    - joblib==1.2.0
    - markdown==3.4.1
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - omegaconf==2.1.1
    - pytorch-lightning==1.5.9
    - requests==2.28.1
    - scipy==1.9.3
    - taming-transformers==0.0.1
    - taming-transformers-rom1504==0.0.6
    - test-tube==0.7.5
    - torch==1.10.2
    - torchvision==0.11.3
    - tqdm==4.64.1
    - urllib3==1.26.13

I did not get any warnings. Any suggestions?

**Comment by zhang-zx** [comment]
Could you also try `pip install -e git+https://github.com/openai/CLIP.git@main#egg=clip` to install the CLIP and `pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers`?
