### ISSUE TITLE
About the initializer_words: ["sculpture"]

### ISSUE THREAD

**Issue by ZrrSkywalker** [zhang-zx/SINE#3]
Hi Thanks for your insightful work!
I'm a little confused about the following two lines in your config files:
        placeholder_strings: ["*"]
        initializer_words: ["sculpture"]
In the paper, it illustrates that the new visual concept is represented by a unique identifier following DreamBooth. Is the code conflict with the paper?
Highly appreciated for your response.

**Comment by zhang-zx** [comment]
Hi, thanks for your interest in our work. Sorry for the confusion. The part of `personalization_config` in the configuration files was not used in the model initialization. Please refer to [here](https://github.com/zhang-zx/SINE/blob/d61d6fae02d08cc5d55611560448270e12b32022/ldm/models/diffusion/ddpm.py#L434-L506) for more details.
