### ISSUE TITLE
How can I fit into 24G VRAM GPU

### ISSUE THREAD

**Issue by winnechan** [zhang-zx/SINE#4]
Hi, thanks for the excellent project. I want to try but with 24G VRAM GPU, which leads to OOM error though with 16fp precision. How can I reduce the GPU memory further? Thanks for any help!

**Comment by zhang-zx** [comment]
Hi, thanks for your interest in our work. We have yet to work on reducing the training GPU memory problem. It might be possible to solve the VRAM problem by implementing the algorithm using Diffusers. We plan to implement it in the future.

**Comment by tau-yihouxiang** [comment]
I encounter the same Memory issue for 24 GB GPU and resizing the image doesn't help.
