### ISSUE TITLE
Prompt for Model-based Image Editing

### ISSUE THREAD

**Issue by GongXinyuu** [zhang-zx/SINE#5]
Hello, thanks for your great work and code!

May I know what is the prompt used during model-based image editing? 
`--prompt "prompt for pre-trained model[SEP]prompt for fine-tuned model"`

For example, I want to use this [pre-trained model](https://drive.google.com/drive/folders/1UHVxbcF5Wnf6ilxVys8Sv8hsbN-4s1Y5?usp=share_link). What is the prompt that I should use? Thanks.

**Comment by zhang-zx** [comment]
Hi, thanks for your interest in our work. For finetuning, we used coarse class names such as dog, girl, etc. So the prompt for the finetuned model would be things like _a picture of a dog_, or _a painting of a girl_. About the prompt for the pre-trained model, it should be the editing instructions. You can refer to our paper for the prompts we used during editing.

**Comment by GongXinyuu** [comment]
Thanks for your kind reply!

I have tried the following command using the provided finetuned checkpoint:
```
python scripts/stable_txt2img_guidance.py --ddim_eta 0.0 --n_iter 1 \
    --ckpt weights/sd-v1-4-full-ema.ckpt \
    --scale 10 --ddim_steps 100 \
    --sin_config configs/stable-diffusion/v1-inference.yaml \
    --sin_ckpt “weights/dog_w_patch/last.ckpt” \
    --prompt “a dog wearing a superhero cape[SEP]picture of a sks dog” \
    --cond_beta 0.4 \
    --range_t_min 500 --range_t_max 1000 --single_guidance \
    --skip_save --H 512 --W 512 --n_samples 2 \
    --outdir output/superhero_dog
```

However, I didn't get promising results. The output images look like this: 
![a-dog-wearing-a-superhero-cape SEP picture-of-a-sks-dog-0000](https://user-images.githubusercontent.com/20336084/211462241-6418b5dc-1461-4e25-a9e0-e93a45dedb15.jpg)

Could you help to check if there's something wrong with my command? Thanks in advance.

**Comment by zhang-zx** [comment]
The checkpoint you're using was fine-tuned with the patch-based schedule. So you may need to choose a different config corresponding to the fine-tuning model.

**Comment by GongXinyuu** [comment]
Thanks! It works.
