### ISSUE TITLE
Strange Results

### ISSUE THREAD

**Issue by ShaoTengLiu** [zhang-zx/SINE#6]
Hi, thanks for this interesting work. I run the scripts on an A100 but get strange results. Could you please give me some hints?

```
IMG_PATH=/data/SINE/DATA/dog.png
CLS_WRD='dog'
NAME='dog_debug'

python main.py \
    --base configs/stable-diffusion/v1-finetune_patch_picture.yaml \
    -t --actual_resume /data/stable-diffusion/sd-v1-4-full-ema.ckpt \
    -n $NAME --gpus 0,   --logdir ./logs \
    --data_root $IMG_PATH \
    --reg_data_root $IMG_PATH --class_word $CLS_WRD
```

```
LOG_DIR=/home/SINE/logs/dog.png2023-01-07T03-25-03_dog_debug
python scripts/stable_txt2img_guidance.py --ddim_eta 0.0 --n_iter 1 \
    --scale 10 --ddim_steps 100 \
    --sin_config configs/stable-diffusion/v1-inference.yaml \
    --sin_ckpt $LOG_DIR"/checkpoints/last.ckpt" \
    --prompt "photo of a dog standing on grass[SEP]photo of a sks dog" \
    --cond_beta 0.4 \
    --range_t_min 500 --range_t_max 1000 --single_guidance \
    --skip_save --H 512 --W 512 --n_samples 2 \
    --outdir $LOG_DIR \
    --ckpt /data/stable-diffusion/sd-v1-4-full-ema.ckpt
```

The results (photo-of-a-dog-standing-on-grass[SEP]photo-of-a-sks-dog-0010.png):
![photo-of-a-dog-standing-on-grass SEP photo-of-a-sks-dog-0010](https://user-images.githubusercontent.com/51499992/211700366-790e1405-b3c6-44e3-8180-6d6f56a3ef2b.jpg)

**Comment by zhang-zx** [comment]
Hi, thanks for your interest in our work. It looks like you encountered the same issue as https://github.com/zhang-zx/SINE/issues/5#issuecomment-1376720706. Please refer to the solution provided.

**Comment by ShaoTengLiu** [comment]
Thank you very much.
