### ISSUE TITLE
Image Editing Results

### ISSUE THREAD

**Issue by GongXinyuu** [zhang-zx/SINE#7]
Hello, Thanks for your great work!

I have tried to reproduce the results using the provided config:
```
IMG_PATH=input/dog/dog.png
CLS_WRD='dog'
NAME='gold_dog_patch'

python main.py \
    --base configs/stable-diffusion/v1-finetune_patch_picture.yaml \
    -t --actual_resume weights/sd-v1-4-full-ema.ckpt \
    -n $NAME --gpus 0,   --logdir ./logs \
    --data_root $IMG_PATH --no_test \
    --reg_data_root $IMG_PATH --class_word $CLS_WRD
```

However, the finetuned model doesn't perform well. The generated images is shown below:
![a coffee machine dog SEP picture of a sks dog_0_mine](https://user-images.githubusercontent.com/20336084/213887971-b79a717c-41b8-4d03-ae02-00667261ab03.png)

The result of provided checkpoint is:
![a coffee machine dog SEP picture of a sks dog_0_orig](https://user-images.githubusercontent.com/20336084/213887985-019bee30-8449-4a3a-8846-0b61febb8385.png)

The inference command I use is:
```
python scripts/stable_txt2img_guidance.py --ddim_eta 0.0 --n_iter 1 \
    --ckpt weights/sd-v1-4-full-ema.ckpt \
    --scale 10 --ddim_steps 100 \
    --sin_config configs/stable-diffusion/v1-inference_patch.yaml \
    --sin_ckpt "logs/dog.png2023-01-17T20-47-28_gold_dog_patch/checkpoints/last.ckpt" \
    --prompt "a coffee machine dog[SEP]picture of a sks dog" \
    --cond_beta 0.4 \
    --range_t_min 500 --range_t_max 1000 --single_guidance \
    --skip_save --H 512 --W 512 --n_samples 1 \
    --outdir logs/dog.png2023-01-17T20-47-28_gold_dog_patch/coffee_gold_dog_patch
```

Could you help to check if there's anything wrong with my training or evaluation command? Thanks.

**Comment by yifanjiang19** [comment]
Hi @zhang-zx ,

Thanks for providing this codebase, I also met the similar issue. Do you know what might be the problem? Thanks!

**Comment by zhang-zx** [comment]
Hi @yifanjiang19 and @GongXinyuu ,
Thanks for your interest in our work. We performed an ablation study on this experiment in Fig.20 on our page. In that figure, we showed how the hyper-parameters influence the model's output. You could refer to that experiment to find a set of parameters to get desired results. Please let us know if you have further questions.

**Comment by yifanjiang19** [comment]
Hi @zhang-zx , thanks so much for pointing out this!

Just wondering if you have kept the correct ckpt of this "coffee machine dog"? So we can quickly try it. Thanks!

**Comment by zhang-zx** [comment]
Hi @yifanjiang19,

I downloaded the ckpt we provided in our project and ran it. The result looks fine. So I think we provided the correct ckpt in the project. Please check again about the environment settings or the parameters you use.

**Comment by yifanjiang19** [comment]
Hi @zhang-zx , can you paste the script you used here for the coffee dog? Thanks!!

**Comment by yifanjiang19** [comment]
NVM, find solution by changing --cond_beta from 0.4 to 0.7
